name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install kubeval
        run: .github/scripts/setup_kubeval.sh
      - name: Test Kubernetes Manifest
        run: |
          ./kubeval --output=stdout -f ./nginx/deployment
